# Generated by Django 5.1.1 on 2026-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_bounding_boxes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_normalized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
